### ISSUE TITLE
New versions of Homebrew forbids calling `brew cask`.

### ISSUE THREAD

**Issue by tslmy** [geerlingguy/mac-dev-playbook#87]
This Issue serves as a tracking ticket.
It is blocked by https://github.com/geerlingguy/ansible-role-homebrew/issues/155 and in turn https://github.com/ansible-collections/community.general/issues/1524.

**Comment by geerlingguy** [comment]
Drat! Thanks for discovering this—I had not even noticed yet as I've been focused on some Pi stuff and haven't run any of my Mac playbooks this week.

**Comment by tslmy** [comment]
ansible-collections/community.general#1524 has been fixed. Closing the ticket.

**Comment by geerlingguy** [comment]
@tslmy - Note that until sometime tomorrow, installs of `ansible` using Pip will still have the older version, meaning the bug will still be present unless you manually update the `community.general` collection in your install with:

```
ansible-galaxy collection install --force git+https://github.com/ansible-collections/community.general.git
```
